#!/bin/sh
# Start/stop the Power Forwarder daemon.
#
### BEGIN INIT INFO
# Provides:          sensorflare_forwarder
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Power Forwarder daemon
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="Sensorflare Forwarder daemon"
NAME=sensorflare_forwarder
DAEMON=/usr/bin/sensorflare_forwarder
PIDFILE=/var/run/sensorflare_forwarder.pid
SCRIPTNAME=/etc/init.d/"$NAME"

test -f $DAEMON || exit 0

. /lib/lsb/init-functions


case "$1" in
start)	log_daemon_msg "Starting $DESC"
        start-stop-daemon -m --start --background --user space -p $PIDFILE --startas $DAEMON --exec $DAEMON
        log_end_msg $?
	;;
stop)	log_daemon_msg "Stopping $DESC"
        start-stop-daemon --stop -p $PIDFILE
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting $DESC"
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)	log_action_msg "Usage: /etc/init.d/sensorflare_forwarder {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0
